# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('*.py', '.'),  # все файлы Python
    ],
    hiddenimports=[
        # PyQt6
        'PyQt6',
        'PyQt6.QtCore',
        'PyQt6.QtWidgets',
        'PyQt6.QtGui',
        'PyQt6.sip',

        # Стандартные модули
        'urllib',
        'urllib.parse',
        'urllib.request',
        'urllib.error',
        'pathlib',
        'zipfile',
        'zipfile._path',
        'csv',
        'json',
        'xml',
        'xml.etree',
        'xml.etree.ElementTree',

        # Ваши модули
        'add_check_dialog',
        'app_window',
        'check_worker',
        'config_editor',
        'document_checker',
        'document_viewer',
        'docx_parser',
        'manage_checks_dialog',
        'settings_dialog',
        'versions_dialog',

        # pandas и зависимости
        'pandas',
        'numpy',
        'openpyxl',
        'pandas._libs',
        'pandas._libs.tslibs',
        'pandas._libs.tslibs.timedeltas',
        'pandas._libs.tslibs.nattype',
        'pandas._libs.tslibs.np_datetime',
        'pandas._libs.tslibs.conversion',
        'pandas._libs.tslibs.base',
        'pandas._libs.tslibs.fields',
        'pandas._libs.tslibs.tzconversion',
        'pandas._libs.tslibs.strptime',
        'pandas._libs.parsers',
        'pandas._libs.lib',
        'pandas._libs.ops',
        'pandas._libs.hashing',
        'pandas._libs.interval',
        'pandas._libs.missing',
        'pandas._libs.properties',
        'pandas._libs.reshape',
        'pandas._libs.window',
        'pandas._libs.index',
        'pandas._libs.internals',
        'pandas._libs.arrays',
        'pandas._libs.groupby',
        'pandas._libs.hashtable',
        'pandas._libs.json',
        'pandas._libs.json_normalize',
        'pandas._libs.join',
        'pandas._libs.merge',
        'pandas._libs.sparse',
        'pandas._libs.testing',
        'pandas.io',
        'pandas.io.common',
        'pandas.io.parsers',
        'pandas.io.json',
        'pandas.io.sql',
        'pandas.io.excel',
        'pandas.io.clipboards',
        'pandas.io.feather_format',
        'pandas.io.gbq',
        'pandas.io.html',
        'pandas.io.orc',
        'pandas.io.parquet',
        'pandas.io.pickle',
        'pandas.io.sas',
        'pandas.io.spss',
        'pandas.io.stata',
        'pandas.util',
        'pandas.plotting',
        'pandas.tseries',
        'pandas.tseries.offsets',
        'pandas.tseries.frequencies',
        'pandas.arrays',
        'pandas.api',
        'pandas.api.types',
        'pandas.api.extensions',
        'pandas.api.indexers',
        'pandas.api.interchange',
        'pandas.core',
        'pandas.core.arrays',
        'pandas.core.common',
        'pandas.core.computation',
        'pandas.core.dtypes',
        'pandas.core.frame',
        'pandas.core.generic',
        'pandas.core.groupby',
        'pandas.core.indexes',
        'pandas.core.internals',
        'pandas.core.resample',
        'pandas.core.series',
        'pandas.core.strings',
        'pandas.core.tools',
        'pandas.core.window',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'tkinter',
        'unittest',
        'pydoc',
        'distutils',
        'venv',
        'ensurepip',
        'lib2to3',
        'test',
        'matplotlib',
        'scipy',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='DocumentChecker',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,  # Установите True для отладки
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None
)